### ISSUE TITLE
CSS alignment with playlists with only a few songs 

### ISSUE THREAD

**Issue by tokyosuite** [Pau1fitz/react-spotify#11]
Hi! I was tinkering around your app when I noticed that short playlists (I think smaller than 3/4 songs) have an overlapping CSS problem. I suspect this is because if the playlist is too short, Spotify doesn't put any pictures. I think maybe a ternary operator of some sort would be able to fix the problem! Awesome project by the way. :) 

<img width="1026" alt="screen shot 2019-01-24 at 5 45 02 pm" src="https://user-images.githubusercontent.com/42653937/51759853-0302e400-207e-11e9-8fbb-36a161fe9993.png">

<img width="1076" alt="screen shot 2019-01-25 at 8 47 09 am" src="https://user-images.githubusercontent.com/42653937/51759869-11e99680-207e-11e9-81c6-1522fc95d4a4.png">

**Comment by Pau1fitz** [comment]
Thanks for this and well spotted. Feel free to play around with the code and make a PR if you fancy it. If not I will look when I get a chance. 😁

**Comment by tokyosuite** [comment]
No problem! What you built is super cool. :)

**Comment by tokyosuite** [comment]
Hi! So I just looked a bit more into the issue - I think it's a problem on
my end, not with your app. I just created a sample playlist with only a
single song, and an image does exist (making the layout is perfectly fine).

The reason why the image doesn't show up for my other playlists is because
they're imported from itunes, which in some sense renders all the songs
unplayable and a default "no-image" for the list. It's a dead playlist,
essentially - and the app crashes when you attempt to play any song on it.

Anyways, sorry for this! You can close the issue.
