### ISSUE TITLE
Invalid element type

### ISSUE THREAD

**Issue by MartijnMillecamp** [Pau1fitz/react-spotify#21]
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `MainView`.

./src/index.js
src/index.js:16
  13 |   applyMiddleware(thunk)
  14 | );
  15 | 
> 16 | ReactDOM.render(
  17 |   <Provider store={store}>
  18 |     <App />
  19 |   </Provider>,

**Comment by Pau1fitz** [comment]
hey @MartijnMillecamp it could be the version of node that you are using.

See this [issue](https://github.com/Pau1fitz/react-spotify/issues/17#issuecomment-612286318).

**Comment by MartijnMillecamp** [comment]
The node version seems not to be the problem :(

**Comment by ddamjengi1020** [comment]
> The node version seems not to be the problem :(

see this [issue](https://github.com/Pau1fitz/react-spotify/issues/17#issuecomment-612286318) solution.
Try copy and paste
I have same issue, but now it working
