### ISSUE TITLE
How audio playback works and some limitations

### ISSUE THREAD

**Issue by Sigmus** [Pau1fitz/react-spotify#3]
First let me thank you for the project. Having fun reading the excellent code.

Took me a while do understand how Spotify playback was made possible:

```this.audio = new Audio(song.track.preview_url);```

A new Audio instance ([Web Audio API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API)) receives a preview_url (which only has 30s of the song):

The app **does not** use the new [Web Playback SDK](https://beta.developer.spotify.com/documentation/web-playback-sdk/) which would enable a full playback experience.

I also couldn't find a refresh_token workflow in the code. Without background refreshing of the token the page would have to be reloaded from time to time (interrupting the experience).

If a developer is considering using this project to start another (like I am) I believe more details on the README.md would facilitate a more informed decision. 

I'm I understanding correctly how the audio playback works? 

Thanks!

**Comment by Pau1fitz** [comment]
You are correct. It uses the `Web Audio API`. This is all handled in the `App.js` file at in [this method](https://github.com/Pau1fitz/react-spotify/blob/master/src/App.js#L71). 

The Spotify API offers 3 authorization flows. In the past I have used the `Authorization Code` flow but for this project I opted for the [`Implicit Grant`](https://developer.spotify.com/web-api/authorization-guide/#implicit-grant-flow) flow . There is a detailed explanation on each of the authorization workflows [here](https://developer.spotify.com/web-api/authorization-guide/).  Spotify also provides examples of each one on their [github account(https://github.com/spotify/web-api-auth-examples).

In this application, if the initial request was `unauthorized` the application will request another token from the API. See [code here](https://github.com/Pau1fitz/react-spotify/blob/master/src/actions/userActions.js#L14). You only have to give the application access to your Spotify account the first time you use it. At that point a cookie is stored on your machine. If you delete this cookie then you will need to authorize the application again, which would interrupt the experience. 

I didn't use the new Web Playback SDK. I had not actually seen this before. Looks like it would definitely be worth implementing. Firstly, I need to get a premium account 😟

**Comment by Sigmus** [comment]
The problem with the Implicit Grant is that if you are playing a music and want to, for example, open a playlist and the token is expired (after maximum 3600s) your browser window will reload in order to refresh the token (and the music stops).

About the new Web Playback SDK: it is VERY new (I haven't been able to make it work locally yet).

**Comment by nukeop** [comment]
@Pau1fitz : does your method allow for more than 30s of playback? Are you able to receive a URL to the stream, or do you have to go through proprietary browser plugins to decrypt music?

**Comment by Sigmus** [comment]
It does not. The the new [Web Playback SDK](https://beta.developer.spotify.com/documentation/web-playback-sdk/) is probably the one you want.

**Comment by nukeop** [comment]
I'm not sure if there's a way to make it work with Electron, which is the use case I'm interested in.
