### ISSUE TITLE
Starting the server

### ISSUE THREAD

**Issue by Mackingzie** [Pau1fitz/react-spotify#6]
I recieve this error:
> node scripts/start.js                                                        
                                                                               
/volume2/web/react-spotify/scripts/start.js:23                                 
const {                                                                        
      ^                                                                        
                                                                               
SyntaxError: Unexpected token {                                                
    at exports.runInThisContext (vm.js:53:16)                                  
    at Module._compile (module.js:373:25)                                      
    at Object.Module._extensions..js (module.js:416:10)                        
    at Module.load (module.js:343:32)                                          
    at Function.Module._load (module.js:300:12)                                
    at Function.Module.runMain (module.js:441:10)                              
    at startup (node.js:140:18)                                                
    at node.js:1043:3                                                          
                                                                               
npm ERR! Linux 3.10.102                                                        
npm ERR! argv "/volume2/@appstore/Node.js_v4/usr/local/bin/node" "/usr/local/bi
npm ERR! node v4.8.4                                                           
npm ERR! npm  v2.15.11                                                         
npm ERR! code ELIFECYCLE                                                       
npm ERR! spotify@0.1.0 start: `node scripts/start.js`                          
npm ERR! Exit status 1                                                         
npm ERR!                                                                       
npm ERR! Failed at the spotify@0.1.0 start script 'node scripts/start.js'.     
npm ERR! This is most likely a problem with the spotify package,               
npm ERR! not with npm itself.                                                  
npm ERR! Tell the author that this fails on your system:                       
npm ERR!     node scripts/start.js                                             
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs spotify                                                  
npm ERR! Or if that isn't available, you can get their info via:               
npm ERR!                                                                       
npm ERR!     npm owner ls spotify                                              
npm ERR! There is likely additional logging output above.                      
                                                                               
npm ERR! Please include the following file with any support request:           
npm ERR!     /volume2/web/react-spotify/npm-debug.log

**Comment by Pau1fitz** [comment]
strange, it's working for me. What version of node are you using? From the log above it looks like it is node `v4.8.4`. It appears that it isn't recognising some ES6 syntax, so I think you will have to upgrade your node version. Try that and let me know if it works.

**Comment by Mackingzie** [comment]
This was the issue!
