### ISSUE TITLE
Callback

### ISSUE THREAD

**Issue by Mackingzie** [Pau1fitz/react-spotify#7]
I got it working with docker on a synology.  The issue I know got is the callback when reauthorization begins.
I get redirected to http://localhost:3000
In the spotify dev section i set the callback to  http://localhost:3000/callback/
Also tried http://{mylocalip}:{port}/callback/ both in spotify and in stat.js
The thing is I'm at http://{mylocalip}:{port} not localhost://3000 and it returns invalid redirect URI

**Comment by Pau1fitz** [comment]
You will need to create new api credentials and add your url as callback url in your spotify dev account. Read through [this tutorial](https://developer.spotify.com/web-api/tutorial/).

You will then need to update [this line ](https://github.com/Pau1fitz/react-spotify/blob/master/src/App.js#L32) with your `token` and `callback url`.

Let me know if you need any help but if you follow the spotify tutorial it should cover everything.

**Comment by Mackingzie** [comment]
It's working like a charm! 
Such a simple solution and I didn't think of the token. Fixed that and it woked.

Thankas for the help!
