### ISSUE TITLE
Songs last 30 seconds

### ISSUE THREAD

**Issue by PabloCastellano** [Pau1fitz/react-spotify#9]
Hi!

Congrats for your project, I just found it and it is really cool :)

I have found weird that I can only listen 30s of the songs in my playlists. Since I have not seen any comment on this in the README file, I wonder - is it a Spotify limitation for third-party apps or is it a limitation in the react-spotify project?

**Comment by Sigmus** [comment]
@PabloCastellano for more check:  https://github.com/Pau1fitz/react-spotify/issues/3

@Pau1fitz It would be really useful for newcomers to specify the limitations in the README.md.

**Comment by Pau1fitz** [comment]
@PabloCastellano @Sigmus thanks for the feedback, I updated the readme :-)

**Comment by PabloCastellano** [comment]
Superb! Thanks
